### ISSUE TITLE
Refactor: 피드 작성 페이지 리팩토링

### ISSUE THREAD

**Issue by somin00** [FoodieLog/foodie-log-client#147]
## 📌 기능
- 피드 작성 페이지 리팩토링

## 🪴 TODO
- [X]  변수 및 함수명 용도 파악 쉽게 수정 
- [X] zustand 객체 구조 분해 할당 방식으로 가져오도록 수정
- [X] 그 외 반복적이거나 불필요한 로직 수정 

## 💡 참고 자료
