### ISSUE TITLE
Refactor: 피드 목록 페이지 리팩토링

### ISSUE THREAD

**Issue by ChoEun-Sang** [FoodieLog/foodie-log-client#148]
## 📌 기능
-  피드 목록 페이지

## 🪴 TODO

- [x]  함수명 네이밍 수정 (-Handler)
- [x]  api를 axios로 정리
- [ ] 기능 단위로 모듈 세분화
- [ ] 상수 정리
- [ ] 기타
