### ISSUE TITLE
Refactor: 맛집 지도 페이지 리팩토링

### ISSUE THREAD

**Issue by JlnHyeok** [FoodieLog/foodie-log-client#149]
## 📌 기능
- 맛집 지도 페이지

## 🪴 TODO
- [x] 중복 코드 제거
- [x] 클릭 기능 버그 수정
- [x] path alias 추가
- [x] #152

**Comment by JlnHyeok** [comment]
맛집 지도 페이지 코드 정리 겸 alias 추가 완료 했습니다.
