### ISSUE TITLE
Refactor: 지역별 맛집 추천 페이지 리팩토링 

### ISSUE THREAD

**Issue by somin00** [FoodieLog/foodie-log-client#151]
## 📌 기능
- 지역별 맛집 추천 페이지 리팩토링

## 🪴 TODO
- [X]  변수 및 함수명 용도 파악 쉽게 수정 
- [X] 컴포넌트 파일에서 타입 분리하기 
- [X] import 별칭 사용
- [X] 그 외 반복적이거나 불필요한 로직 수정
