### ISSUE TITLE
Refactor: 개인 정보 수정 페이지 리팩토링

### ISSUE THREAD

**Issue by somin00** [FoodieLog/foodie-log-client#157]
## 📌 기능
- 개인 정보 수정 페이지 리팩토링

## 🪴 TODO
- [X]  함수 로직 정리 
- [X] 변수 및 함수명 수정
- [X] import 정리 및 별칭 사용
