### ISSUE TITLE
Refactor: 피드 작성, 지역 맛집 추천, 개인 정보 수정 api 리팩토링

### ISSUE THREAD

**Issue by somin00** [FoodieLog/foodie-log-client#159]
## 📌 기능
- 담당 페이지와 관련된 api 리팩토링 

## 🪴 TODO
- [ ]  사용하지 않는 request 제거
- [ ] 요청 방법 axios로 통일
- [ ] api 코드 정리
