### ISSUE TITLE
Refactor: 피드 작성 페이지 디자인 수정

### ISSUE THREAD

**Issue by somin00** [FoodieLog/foodie-log-client#175]
## 📌 기능
- 피드 작성 페이지 디자인 수정

## 🪴 TODO
- [ ] 음식점 검색 컴포넌트 디자인 수정
- [ ] 이미지 첨부 컴포넌트 디자인 수정
- [ ] 피드 내용 작성 컴포넌트 디자인 수정
