### ISSUE TITLE
Refactor: 피드 페이지 스타일 수정 및 리팩토링 

### ISSUE THREAD

**Issue by ChoEun-Sang** [FoodieLog/foodie-log-client#179]
## 📌 기능
- 피드 페이지 

## 🪴 TODO

- [ ]  반복되는 DataFetcing 로직을 커스텀 훅으로 분리하기
- [ ]  피드 페이지 스타일 수정
- [ ] 기타 코드 리팩토링
