### ISSUE TITLE
Refactor: 팔로우 버튼 스타일 수정 및 모듈화

### ISSUE THREAD

**Issue by ChoEun-Sang** [FoodieLog/foodie-log-client#183]
## 📌 기능
- 기존 피드 컴포넌트 내 결합된 팔로우 버튼 모듈화 작업
- 재사용성과 유지보수성 고려한 리팩토링

## 🪴 TODO

- [ ]  팔로우 버튼 모듈화
- [ ]  팔로우 Fetcing 커스텀 훅으로 분리
- [ ]  버튼 스타일 수정
- [ ]  팔로우 상태 변경 오류 해결

## 💡 참고 자료
<img width="179" alt="스크린샷 2024-03-02 오전 12 03 29" src="https://github.com/FoodieLog/foodie-log-client/assets/128155681/e1994bb5-f33d-40d2-8bdf-b6950e31bc34">
