### ISSUE TITLE
Refactor: 설정 및 개인 정보 수정 페이지 디자인 수정 

### ISSUE THREAD

**Issue by somin00** [FoodieLog/foodie-log-client#185]
## 📌 기능
- 설정 및 개인 정보 수정 페이지 디자인 수정 

## 🪴 TODO
- [ ] 개인 정보 수정 페이지 디자인 수정 
- [ ]  뱃지 신청 페이지 디자인 수정
- [ ] 비밀번호 변경 페이지 디자인 수정
