### ISSUE TITLE
Feat: 푸시 알림 기능 구현

### ISSUE THREAD

**Issue by ChoEun-Sang** [FoodieLog/foodie-log-client#198]
## 📌 기능
- 푸시 알림 기능 구현

## 🪴 TODO

- [x]  푸시 알림 UI 구현
- [x]  전체 알림 설정 로직 수정
- [ ] 댓글, 좋아요, 팔로우 세부 알림 설정 구현
- [x] 코드 리팩토링
