### ISSUE TITLE
Design: 담당 페이지 디자인 수정

### ISSUE THREAD

**Issue by somin00** [FoodieLog/foodie-log-client#218]
## 📌 기능
- 담당 페이지 디자인 수정 

## 🪴 TODO
- [ ]  뱃지 신청 페이지 디자인 수정 
- [ ] 피드 수정 페이지 체크박스 제거
- [ ] 식당 피드 썸네일 페이지 이미지 영역 추가
