### ISSUE TITLE
Fix: 배포 오류 수정 및 기타 코드 수정

### ISSUE THREAD

**Issue by ChoEun-Sang** [FoodieLog/foodie-log-client#237]
## 📌 기능
- 배포 오류 수정 및 기타 코드 수정

## 🪴 TODO

- [x]  localStorage is not defined 에러 해결
- [x]  팔로우 뮤테이션 무효화 수정
- [x]  알림 피드 url 수정
- [x] 기타 코드 수정
